In [1]:
import numpy as np
x = np.array([[0,0], [0,1], [1,0], [1,1]])
y = np.array([0,1,1,1])
x

array([[0, 0],
       [0, 1],
       [1, 0],
       [1, 1]])

In [3]:
y

array([0, 1, 1, 1])

In [5]:
w = np.array([1, 1])

In [7]:
w

array([1, 1])

In [9]:
b = -0.5

In [11]:
pred = []

In [21]:
def activation(z):
    if z >= 0:
        return 1
    else: 
        return 0

In [23]:
for a in x:
    y_hat = np.dot(a, w) + b
    pred.append(activation(y_hat))

In [25]:
pred

[0, 1, 1, 1]

In [33]:
import math
import numpy as np

In [37]:
epochs = 100
alpha = 0.2

In [41]:
w0 = np.random.random()
w1 = np.random.random()
w2 = np.random.random()
print("initial weights:")
print("w0= ", w0, "w1= ",w1, "w2 = ",w2)

initial weights:
w0=  0.8568297763833596 w1=  0.9305467408009859 w2 =  0.935607906816058


In [43]:
del_w0 = 1
del_w1 = 1
del_w2 = 1

In [47]:
train_data_temp = [[0,0,0], [0,0,1], [0,1,0],[0,1,1],[1,0,0],[1,0,1],[1,1,0],[1,1,1]]
train_data = np.asarray(train_data_temp)
op = np.array([0,1,1,1,1,1,1,1])

In [49]:
train_data

array([[0, 0, 0],
       [0, 0, 1],
       [0, 1, 0],
       [0, 1, 1],
       [1, 0, 0],
       [1, 0, 1],
       [1, 1, 0],
       [1, 1, 1]])

In [51]:
op

array([0, 1, 1, 1, 1, 1, 1, 1])

In [53]:
#y=x*w+b

In [61]:
bias = 0
for i in range(epochs):
    j =0
    for x in train_data:
        y_hat = w0*x[0]+w1*x[1]+w2*x[2]+ bias

        if(y_hat >= 0):
            act = 1
        else : 
            act = 0

        err = op[j] = act

        del_w0 = alpha*x[0]*err
        del_w1 = alpha*x[1]*err
        del_w2 = alpha*x[2]*err

        w0 = w0 + del_w0
        w1 = w1 + del_w1
        w2 = w2 + del_w2
        j = j+1
        print("epoch", i+1, "error = ", err)
        print(del_w0, del_w1, del_w2)

print("\nFinal Weithts = ")
print("w0= ", w0, "w1= ",w1, "w2 = ",w2)

epoch 1 error =  1
0.0 0.0 0.0
epoch 1 error =  1
0.0 0.0 0.2
epoch 1 error =  1
0.0 0.2 0.0
epoch 1 error =  1
0.0 0.2 0.2
epoch 1 error =  1
0.2 0.0 0.0
epoch 1 error =  1
0.2 0.0 0.2
epoch 1 error =  1
0.2 0.2 0.0
epoch 1 error =  1
0.2 0.2 0.2
epoch 2 error =  1
0.0 0.0 0.0
epoch 2 error =  1
0.0 0.0 0.2
epoch 2 error =  1
0.0 0.2 0.0
epoch 2 error =  1
0.0 0.2 0.2
epoch 2 error =  1
0.2 0.0 0.0
epoch 2 error =  1
0.2 0.0 0.2
epoch 2 error =  1
0.2 0.2 0.0
epoch 2 error =  1
0.2 0.2 0.2
epoch 3 error =  1
0.0 0.0 0.0
epoch 3 error =  1
0.0 0.0 0.2
epoch 3 error =  1
0.0 0.2 0.0
epoch 3 error =  1
0.0 0.2 0.2
epoch 3 error =  1
0.2 0.0 0.0
epoch 3 error =  1
0.2 0.0 0.2
epoch 3 error =  1
0.2 0.2 0.0
epoch 3 error =  1
0.2 0.2 0.2
epoch 4 error =  1
0.0 0.0 0.0
epoch 4 error =  1
0.0 0.0 0.2
epoch 4 error =  1
0.0 0.2 0.0
epoch 4 error =  1
0.0 0.2 0.2
epoch 4 error =  1
0.2 0.0 0.0
epoch 4 error =  1
0.2 0.0 0.2
epoch 4 error =  1
0.2 0.2 0.0
epoch 4 error =  1
0.2 0.2 0.2
epoch 5 