In [1]:
import torch
print(torch.__version__)

2.6.0+cu124


In [3]:
if torch.cuda.is_available():
    print("CUDA is available.")
    print(f"Using GPU: {torch.cuda.get_device_name(0)}")
else:
    print("CUDA is not available.")

CUDA is available.
Using GPU: Tesla T4


## Creating a Tensor

In [9]:
# using empty
a = torch.empty(2,3) # it allocate memory and it gives value default avaiable at that space
a

tensor([[2.1707e-18, 7.0952e+22, 1.7748e+28],
        [1.8176e+31, 7.2708e+31, 5.0778e+31]])

In [7]:
# check type
type(a)

torch.Tensor

In [8]:
# using zeros
torch.zeros(2,3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [10]:
torch.ones(2,3)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [16]:
torch.rand(2,3) # every time new random value

tensor([[0.2627, 0.0428, 0.2080],
        [0.1180, 0.1217, 0.7356]])

In [17]:
# use of seed : it initialize same random value for each time
torch.manual_seed(100)
torch.rand(2,3)

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

In [19]:
# using tensor
torch.tensor([[1,2,3],[4,5,6]])

tensor([[1, 2, 3],
        [4, 5, 6]])

In [20]:
# other ways
## arrange
torch.arange(0,10,2) # 0 to 10 with jump 2

tensor([0, 2, 4, 6, 8])

In [21]:
# linspace
torch.linspace(0,10,5) # 0 to 10 with 5 values

tensor([ 0.0000,  2.5000,  5.0000,  7.5000, 10.0000])

In [22]:
# eye
torch.eye(5) # identity matrix

tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])

In [23]:
# full
torch.full((2,3),4) # 2x3 matrix with value 4

tensor([[4, 4, 4],
        [4, 4, 4]])

## Tensor Shapes

In [25]:
x = torch.tensor([[1,2,3],[4,5,6]])
x

tensor([[1, 2, 3],
        [4, 5, 6]])

In [26]:
x.shape

torch.Size([2, 3])

In [27]:
torch.empty_like(x) # empty tensor but same shape of x

tensor([[243417,      2,      3],
        [     4,      5,      6]])

In [28]:
torch.zeros_like(x)

tensor([[0, 0, 0],
        [0, 0, 0]])

In [29]:
torch.ones_like(x)

tensor([[1, 1, 1],
        [1, 1, 1]])

In [32]:
# torch.rand_like(x) <--- we define x with integer but rand generate float also so error came
# so we need to learn data types

## Tensor Datatypes

In [33]:
# find data type
x.dtype

torch.int64

In [34]:
# assign data_type
torch.tensor([1.0,2.0,3.0], dtype=torch.int32)

tensor([1, 2, 3], dtype=torch.int32)

In [35]:
torch.tensor([1,2,3], dtype=torch.float64)

tensor([1., 2., 3.], dtype=torch.float64)

In [36]:
# using to()
x.to(torch.float32)

tensor([[1., 2., 3.],
        [4., 5., 6.]])

In [37]:
 torch.rand_like(x, dtype=torch.float64)

tensor([[0.1015, 0.6642, 0.9736],
        [0.6941, 0.3464, 0.9751]], dtype=torch.float64)

## Mathematical Operation

### Scalar Operation

In [39]:
x = torch.rand(2,2)
x

tensor([[0.5557, 0.9770],
        [0.4440, 0.9478]])

In [45]:
# addition
x + 2
# substraction
x - 2
# multiplication
x * 3
# division
x / 3
# int division
(x * 100)//3
# mod
((x * 100)//3)%2
# power
x ** 2

tensor([[0.3089, 0.9546],
        [0.1972, 0.8984]])

### element wise operation

In [46]:
a = torch.rand(2,3)
b = torch.rand(2,3)

print(a)
print(b)

tensor([[0.7445, 0.4892, 0.2426],
        [0.7003, 0.5277, 0.2472]])
tensor([[0.7909, 0.4235, 0.0169],
        [0.2209, 0.9535, 0.7064]])


In [52]:
# add
a + b
# sub
a - b
a * b
a / b
a ** b
a % b

tensor([[0.7445, 0.0657, 0.0060],
        [0.0377, 0.5277, 0.2472]])

In [53]:
c = torch.tensor([1, -2, 3, -4])

In [54]:
torch.abs(c)

tensor([1, 2, 3, 4])

In [55]:
torch.neg(c)

tensor([-1,  2, -3,  4])

In [56]:
d = torch.tensor([1.9, 2.3, 3.7])

In [57]:
torch.round(d)

tensor([2., 2., 4.])

In [59]:
# ceil -> go to upper integer
torch.ceil(d)

tensor([2., 3., 4.])

In [61]:
# floor -> go to lower integer
torch.floor(d)

tensor([1., 2., 3.])

In [63]:
# clamp -> stay in range
torch.clamp(d, min=2, max=3)

tensor([2.0000, 2.3000, 3.0000])

### Reduction operation

In [64]:
e = torch.randint(size=(2,3), low=0, high=10)
e

tensor([[4, 0, 5],
        [7, 5, 9]])

In [65]:
# sum
torch.sum(e)

tensor(30)

In [66]:
# sum along columns
torch.sum(e, dim=0)

tensor([11,  5, 14])

In [67]:
# sum anong rows
torch.sum(e, dim=1)

tensor([ 9, 21])

In [69]:
# mean
e = torch.randint(size=(2,3), low=0, high=10, dtype=torch.float32)
e
torch.mean(e)

tensor(7.8333)

In [70]:
torch.mean(e, dim=0)

tensor([9.0000, 7.5000, 7.0000])

In [71]:
# median
torch.median(e)

tensor(8.)

In [72]:
# product
torch.prod(e)

tensor(204120.)

In [73]:
#SD
torch.std(e)

tensor(1.6021)

In [74]:
# variance
torch.var(e)

tensor(2.5667)

In [75]:
# argmax <- show posion of largest item
torch.argmax(e)

tensor(0)

In [76]:
e

tensor([[9., 7., 5.],
        [9., 8., 9.]])

In [77]:
torch.argmin(e)

tensor(2)

### matrix operaition

In [78]:
f = torch.randint(size=(2,3), low=0, high=10)
g = torch.randint(size=(3,2), low=0, high=10)
print(f)
print(g)

tensor([[7, 9, 2],
        [6, 7, 7]])
tensor([[8, 3],
        [6, 1],
        [5, 5]])


In [79]:
# matrix multiplication
torch.matmul(f, g)

tensor([[120,  40],
        [125,  60]])

In [81]:
vector1 = torch.tensor([1,2,3])
vector2 = torch.tensor([4,5,6])

print(vector1)
print(vector2)

tensor([1, 2, 3])
tensor([4, 5, 6])


In [82]:
torch.dot(vector1, vector2)

tensor(32)

In [83]:
# transpose
torch.transpose(f, 0, 1)

tensor([[7, 6],
        [9, 7],
        [2, 7]])

In [86]:
h = torch.randint(size=(3,3), low=0, high=10, dtype=torch.float32)
h

tensor([[0., 4., 3.],
        [8., 8., 3.],
        [3., 5., 0.]])

In [87]:
# determinant
torch.det(h)

tensor(84.)

### Comparision operations

In [88]:
i = torch.randint(size=(2,3), low=0, high=10)
j = torch.randint(size=(2,3), low=0, high=10)
print(i)
print(j)

tensor([[6, 4, 0],
        [8, 4, 7]])
tensor([[2, 3, 8],
        [5, 6, 2]])


In [89]:
i>j

tensor([[ True,  True, False],
        [ True, False,  True]])

In [90]:
i<j

tensor([[False, False,  True],
        [False,  True, False]])

In [91]:
i==j

tensor([[False, False, False],
        [False, False, False]])

In [92]:
i!= j

tensor([[True, True, True],
        [True, True, True]])

### Special functions

In [93]:
k = torch.randint(size=(2,3), low=0, high=10)
k

tensor([[9, 5, 0],
        [4, 2, 7]])

In [94]:
torch.log(k)

tensor([[2.1972, 1.6094,   -inf],
        [1.3863, 0.6931, 1.9459]])

In [95]:
torch.exp(k)

tensor([[8.1031e+03, 1.4841e+02, 1.0000e+00],
        [5.4598e+01, 7.3891e+00, 1.0966e+03]])

In [96]:
torch.sqrt(k)

tensor([[3.0000, 2.2361, 0.0000],
        [2.0000, 1.4142, 2.6458]])

In [97]:
torch.sigmoid(x)

tensor([[0.6355, 0.7265],
        [0.6092, 0.7207]])

In [99]:
k = torch.randint(size=(2,3), low=0, high=10, dtype=torch.float32)
torch.softmax(k, dim=0)

tensor([[0.0474, 0.0474, 0.9820],
        [0.9526, 0.9526, 0.0180]])

In [100]:
torch.relu(k)

tensor([[1., 1., 5.],
        [4., 4., 1.]])

### Inplace Operations

In [101]:
m = torch.rand(2, 3)
n = torch.rand(2, 3)
print(m)
print(n)

tensor([[0.3011, 0.1893, 0.9186],
        [0.2131, 0.3957, 0.6017]])
tensor([[0.4234, 0.5224, 0.4175],
        [0.0340, 0.9157, 0.3079]])


In [102]:
m + n # <- it add element wise operation and stored result also in tensor, it means it stored in some memory i.e it need space for m, n and for result.

tensor([[0.7245, 0.7117, 1.3361],
        [0.2472, 1.3114, 0.9096]])

In [103]:
# we need m + n and we need to store result on m then
m.add_(n)

tensor([[0.7245, 0.7117, 1.3361],
        [0.2472, 1.3114, 0.9096]])

In [104]:
print(m)
print(n)

tensor([[0.7245, 0.7117, 1.3361],
        [0.2472, 1.3114, 0.9096]])
tensor([[0.4234, 0.5224, 0.4175],
        [0.0340, 0.9157, 0.3079]])


In [107]:
torch.relu(m) # <- result on new memory
m.relu_() # - result on m

tensor([[0.7245, 0.7117, 1.3361],
        [0.2472, 1.3114, 0.9096]])

### Copying a tensor

In [108]:
n = torch.rand(2,3)
n

tensor([[0.6269, 0.8277, 0.6594],
        [0.0887, 0.4890, 0.5887]])

In [110]:
o = n

In [111]:
o

tensor([[0.6269, 0.8277, 0.6594],
        [0.0887, 0.4890, 0.5887]])

In [112]:
n[0][0] =0
n

tensor([[0.0000, 0.8277, 0.6594],
        [0.0887, 0.4890, 0.5887]])

In [115]:
o # <- we have also first term in o is zero, i.e o = n is not make copy, it makes just new pointer to old value.

tensor([[0.0000, 0.8277, 0.6594],
        [0.0887, 0.4890, 0.5887]])

In [117]:
id(o)

132574702660752

In [118]:
id(n)

132574702660752

In [119]:
o = n.clone()

In [120]:
print(o)
print(n)

tensor([[0.0000, 0.8277, 0.6594],
        [0.0887, 0.4890, 0.5887]])
tensor([[0.0000, 0.8277, 0.6594],
        [0.0887, 0.4890, 0.5887]])


In [121]:
n[0][1] =0

In [122]:
print(o)
print(n)

tensor([[0.0000, 0.8277, 0.6594],
        [0.0887, 0.4890, 0.5887]])
tensor([[0.0000, 0.0000, 0.6594],
        [0.0887, 0.4890, 0.5887]])


In [123]:
id(o)

132574702658736

In [124]:
id(n)

132574702660752

### Tensor Operations on GPU

In [125]:
torch.cuda.is_available()

True

In [126]:
device = torch.device("cuda")

In [128]:
# creating a new tensor on GPU
torch.rand((2,3), device=device)

tensor([[0.3563, 0.0303, 0.7088],
        [0.2009, 0.0224, 0.9896]], device='cuda:0')

In [129]:
# moving an existing tensor to GPU
a = torch.rand((2,3))
a

tensor([[0.7340, 0.8497, 0.9112],
        [0.4847, 0.9436, 0.3904]])

In [131]:
b = a.to(device)

In [132]:
b + 5

tensor([[5.7340, 5.8497, 5.9112],
        [5.4847, 5.9436, 5.3904]], device='cuda:0')

### Comparision time between runing on CPU vs GPU

In [133]:
import time

size = 10000 # size of matrix

# create random matrices on CPU
m_cpu1 = torch.rand(size, size)
m_cpu2 = torch.rand(size, size)

# measure time
start = time.time()
result_cpu = torch.matmul(m_cpu1, m_cpu2)
end = time.time()

print(f"CPU time: {end - start} seconds")

# move matrices to GPU
m_gpu1 = m_cpu1.to("cuda")
m_gpu2 = m_cpu2.to("cuda")

# measure time
start = time.time()
result_gpu = torch.matmul(m_gpu1, m_gpu2)
torch.cuda.synchronize() # ensure all GPU operation are complete
end = time.time()

print(f"GPU time: {end - start} seconds")



CPU time: 16.464959621429443 seconds
GPU time: 0.6987400054931641 seconds


### Reshaping Tensors

In [134]:
a = torch.ones(4,4)
a

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [135]:
# reshape
a.reshape(2,2,2,2)

tensor([[[[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]]],


        [[[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]]]])

In [136]:
a.flatten()

tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [139]:
b = torch.rand(2,3,4)
b

tensor([[[0.3265, 0.6684, 0.3509, 0.7772],
         [0.2353, 0.4301, 0.4385, 0.7375],
         [0.5494, 0.7109, 0.0148, 0.7262]],

        [[0.4660, 0.0610, 0.7108, 0.5127],
         [0.8211, 0.1323, 0.2127, 0.9785],
         [0.3362, 0.7165, 0.1591, 0.2860]]])

In [140]:
# permute
b_permute = b.permute(2,0,1) # shape of index 2 is come to zero index, index 0 to index 1 and index 1 to index 2

In [142]:
print(b.shape)
print(b_permute.shape)

torch.Size([2, 3, 4])
torch.Size([4, 2, 3])


In [145]:
# unsqueeze <- add new dimension at position
c = torch.rand(226, 226, 3)
c.unsqueeze(0).shape # 0 is position

torch.Size([1, 226, 226, 3])

In [146]:
# squeeze
d = torch.rand(1, 20)
d.squeeze(0).shape

torch.Size([20])

## Numpy and Pytorch

In [147]:
import numpy as np

In [149]:
a = torch.tensor([1,2,3])
a

tensor([1, 2, 3])

In [151]:
b = a.numpy()
b

array([1, 2, 3])

In [152]:
type(b)

numpy.ndarray

In [153]:
c = np.array([1,2,3])
c

array([1, 2, 3])

In [154]:
torch.from_numpy(c)

tensor([1, 2, 3])