In [1]:
import numpy as np
import pandas as pd
import torch
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder

In [ ]:
df = pd.read_csv('https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv')
df.head()

id diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0    842302         M        17.99         10.38          122.80     1001.0   
1    842517         M        20.57         17.77          132.90     1326.0   
2  84300903         M        19.69         21.25          130.00     1203.0   
3  84348301         M        11.42         20.38           77.58      386.1   
4  84358402         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   ...  texture_worst  perimeter_worst  area_worst  smoothness_worst  \
0  ...          17.33           184.60      2019.0            0.1622   
1  ...          23.41           158.80      1956.0            0.1238   
2  ...          25.53           152.50      1709.0            0.1444   
3  ...          26.50            98.87       567.7            0.2098   
4  ...          16.67           152.20      1575.0            0.1374   

   compactness_worst  concavity_worst  concave points_worst  symmetry_worst  \
0             0.6656           0.7119                0.2654          0.4601   
1             0.1866           0.2416                0.1860          0.2750   
2             0.4245           0.4504                0.2430          0.3613   
3             0.8663           0.6869                0.2575          0.6638   
4             0.2050           0.4000                0.1625          0.2364   

   fractal_dimension_worst  Unnamed: 32  
0                  0.11890          NaN  
1                  0.08902          NaN  
2                  0.08758          NaN  
3                  0.17300          NaN  
4                  0.07678          NaN  

[5 rows x 33 columns]

In [ ]:
df.shape

(569, 33)

In [ ]:
df.columns

Index(['id', 'diagnosis', 'radius_mean', 'texture_mean', 'perimeter_mean',
       'area_mean', 'smoothness_mean', 'compactness_mean', 'concavity_mean',
       'concave points_mean', 'symmetry_mean', 'fractal_dimension_mean',
       'radius_se', 'texture_se', 'perimeter_se', 'area_se', 'smoothness_se',
       'compactness_se', 'concavity_se', 'concave points_se', 'symmetry_se',
       'fractal_dimension_se', 'radius_worst', 'texture_worst',
       'perimeter_worst', 'area_worst', 'smoothness_worst',
       'compactness_worst', 'concavity_worst', 'concave points_worst',
       'symmetry_worst', 'fractal_dimension_worst', 'Unnamed: 32'],
      dtype='object')

In [ ]:
df.drop(columns=["id", "Unnamed: 32"], inplace=True)

In [ ]:
df.head()

diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0         M        17.99         10.38          122.80     1001.0   
1         M        20.57         17.77          132.90     1326.0   
2         M        19.69         21.25          130.00     1203.0   
3         M        11.42         20.38           77.58      386.1   
4         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   symmetry_mean  ...  radius_worst  texture_worst  perimeter_worst  \
0         0.2419  ...         25.38          17.33           184.60   
1         0.1812  ...         24.99          23.41           158.80   
2         0.2069  ...         23.57          25.53           152.50   
3         0.2597  ...         14.91          26.50            98.87   
4         0.1809  ...         22.54          16.67           152.20   

   area_worst  smoothness_worst  compactness_worst  concavity_worst  \
0      2019.0            0.1622             0.6656           0.7119   
1      1956.0            0.1238             0.1866           0.2416   
2      1709.0            0.1444             0.4245           0.4504   
3       567.7            0.2098             0.8663           0.6869   
4      1575.0            0.1374             0.2050           0.4000   

   concave points_worst  symmetry_worst  fractal_dimension_worst  
0                0.2654          0.4601                  0.11890  
1                0.1860          0.2750                  0.08902  
2                0.2430          0.3613                  0.08758  
3                0.2575          0.6638                  0.17300  
4                0.1625          0.2364                  0.07678  

[5 rows x 31 columns]

In [ ]:
df.columns

Index(['diagnosis', 'radius_mean', 'texture_mean', 'perimeter_mean',
       'area_mean', 'smoothness_mean', 'compactness_mean', 'concavity_mean',
       'concave points_mean', 'symmetry_mean', 'fractal_dimension_mean',
       'radius_se', 'texture_se', 'perimeter_se', 'area_se', 'smoothness_se',
       'compactness_se', 'concavity_se', 'concave points_se', 'symmetry_se',
       'fractal_dimension_se', 'radius_worst', 'texture_worst',
       'perimeter_worst', 'area_worst', 'smoothness_worst',
       'compactness_worst', 'concavity_worst', 'concave points_worst',
       'symmetry_worst', 'fractal_dimension_worst'],
      dtype='object')

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(df.iloc[:, 1:], df.iloc[:, 0], test_size=0.2)

In [ ]:
X_train

radius_mean  texture_mean  perimeter_mean  area_mean  smoothness_mean  \
445       11.990         24.89           77.61      441.3          0.10300   
176        9.904         18.06           64.60      302.4          0.09699   
242       11.300         18.19           73.93      389.4          0.09592   
409       12.270         17.92           78.41      466.1          0.08685   
328       16.270         20.71          106.90      813.7          0.11690   
..           ...           ...             ...        ...              ...   
290       14.410         19.73           96.03      651.0          0.08757   
337       18.770         21.43          122.90     1092.0          0.09116   
481       13.900         19.24           88.73      602.9          0.07991   
521       24.630         21.60          165.50     1841.0          0.10300   
407       12.850         21.37           82.63      514.5          0.07551   

     compactness_mean  concavity_mean  concave points_mean  symmetry_mean  \
445           0.09218         0.05441              0.04274         0.1820   
176           0.12940         0.13070              0.03716         0.1669   
242           0.13250         0.15480              0.02854         0.2054   
409           0.06526         0.03211              0.02653         0.1966   
328           0.13190         0.14780              0.08488         0.1948   
..                ...             ...                  ...            ...   
290           0.16760         0.13620              0.06602         0.1714   
337           0.14020         0.10600              0.06090         0.1953   
481           0.05326         0.02995              0.02070         0.1579   
521           0.21060         0.23100              0.14710         0.1991   
407           0.08316         0.06126              0.01867         0.1580   

     fractal_dimension_mean  ...  radius_worst  texture_worst  \
445                 0.06850  ...         12.98          30.36   
176                 0.08116  ...         11.26          24.39   
242                 0.07669  ...         12.58          27.96   
409                 0.05597  ...         14.10          28.88   
328                 0.06277  ...         19.28          30.38   
..                      ...  ...           ...            ...   
290                 0.07192  ...         15.77          22.13   
337                 0.06083  ...         24.54          34.37   
481                 0.05594  ...         16.41          26.42   
521                 0.06739  ...         29.92          26.93   
407                 0.06114  ...         14.40          27.01   

     perimeter_worst  area_worst  smoothness_worst  compactness_worst  \
445            84.48       513.9           0.13110             0.1822   
176            73.07       390.2           0.13010             0.2950   
242            87.16       472.9           0.13470             0.4848   
409            89.00       610.2           0.12400             0.1795   
328           129.80      1121.0           0.15900             0.2947   
..               ...         ...               ...                ...   
290           101.70       767.3           0.09983             0.2472   
337           161.10      1873.0           0.14980             0.4827   
481           104.40       830.5           0.10640             0.1415   
521           205.70      2642.0           0.13420             0.4188   
407            91.63       645.8           0.09402             0.1936   

     concavity_worst  concave points_worst  symmetry_worst  \
445           0.1609               0.12020          0.2599   
176           0.3486               0.09910          0.2614   
242           0.7436               0.12180          0.3308   
409           0.1377               0.09532          0.3455   
328           0.3597               0.15830          0.3103   
..               ...                   ...             ...   
290           0.2220               0.10210         

In [ ]:
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [ ]:
X_train

array([[-0.6325044 ,  1.39846425, -0.61531761, ...,  0.0975638 ,
        -0.47533952, -0.05071913],
       [-1.21948248, -0.27095053, -1.14610456, ..., -0.23183719,
        -0.45053227,  1.88045388],
       [-0.82666301, -0.23917544, -0.76545566, ...,  0.12254207,
         0.69721624,  2.65429881],
       ...,
       [-0.09505083,  0.01746959, -0.1616396 , ..., -0.5065982 ,
        -0.87721688, -0.42216469],
       [ 2.92425637,  0.59430984,  2.97045219, ...,  2.0848977 ,
         0.44748998,  0.7632511 ],
       [-0.3905096 ,  0.53809235, -0.41050973, ..., -0.90453332,
        -0.65891313, -0.10804097]])

In [ ]:
y_train

445    B
176    B
242    B
409    B
328    M
      ..
290    B
337    M
481    B
521    M
407    B
Name: diagnosis, Length: 455, dtype: object

## label encoding

In [ ]:
encoder = LabelEncoder()
y_train = encoder.fit_transform(y_train)
y_test = encoder.transform(y_test)

In [ ]:
y_train

array([0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 1,
       0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0,
       0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0,
       0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1,
       0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0,
       0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1,
       0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1,
       0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0,
       0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1,

## Numpy arrays to PyTorch tensors

In [ ]:
X_train_tensor = torch.from_numpy(X_train)
X_test_tensor = torch.from_numpy(X_test)
y_train_tensor = torch.from_numpy(y_train)
y_test_tensor = torch.from_numpy(y_test)

In [ ]:
X_train_tensor

tensor([[-0.6325,  1.3985, -0.6153,  ...,  0.0976, -0.4753, -0.0507],
        [-1.2195, -0.2710, -1.1461,  ..., -0.2318, -0.4505,  1.8805],
        [-0.8267, -0.2392, -0.7655,  ...,  0.1225,  0.6972,  2.6543],
        ...,
        [-0.0951,  0.0175, -0.1616,  ..., -0.5066, -0.8772, -0.4222],
        [ 2.9243,  0.5943,  2.9705,  ...,  2.0849,  0.4475,  0.7633],
        [-0.3905,  0.5381, -0.4105,  ..., -0.9045, -0.6589, -0.1080]],
       dtype=torch.float64)

In [ ]:
y_train_tensor.shape

torch.Size([455])

In [ ]:
X_train_tensor.shape

torch.Size([455, 30])

## Defining the model

In [ ]:
class MySimpleNN():

  def __init__(self, X):

    self.weights = torch.rand(X.shape[1], 1, dtype=torch.float64, requires_grad=True)
    self.bias = torch.zeros(1, dtype=torch.float64, requires_grad=True)

  def forward(self, X):
    z = torch.matmul(X, self.weights) + self.bias
    y_pred = torch.sigmoid(z)
    return y_pred

  def loss(self, y_pred, y):
    # clamp predictions to avoids log(0)
    epsilon = 1e-7
    y_pred = torch.clamp(y_pred, epsilon, 1 - epsilon)
    loss = -(y_train_tensor * torch.log(y_pred) + (1 - y_train_tensor) * torch.log(1 - y_pred)).mean()
    return loss



## Important Parameters

In [ ]:
learning_rate = 0.1
epochs = 100

## Training Pipeline

In [ ]:
# create Model
model = MySimpleNN(X_train_tensor)
# define loop
for epoch in range(epochs):
  # forward pass
  y_pred = model.forward(X_train_tensor)

  # loss calculate
  loss = model.loss(y_pred, y_train_tensor)

  # backward pass
  loss.backward() # using autogard

  # parameters update
  with torch.no_grad():
    model.weights -= learning_rate * model.weights.grad
    model.bias -= learning_rate * model.bias.grad

  # zero gradients
  model.weights.grad.zero_()
  model.bias.grad.zero_()

  # print loss in each epoch
  print(f'Epoch: {epoch + 1}, loss: {loss.item()}')

Epoch: 1, loss: 3.0661334985088273
Epoch: 2, loss: 2.9227792291653283
Epoch: 3, loss: 2.775917986783345
Epoch: 4, loss: 2.6218134730181015
Epoch: 5, loss: 2.464188296798678
Epoch: 6, loss: 2.29911580672197
Epoch: 7, loss: 2.1308532966279334
Epoch: 8, loss: 1.9608064284084037
Epoch: 9, loss: 1.791102071866371
Epoch: 10, loss: 1.6231444680721623
Epoch: 11, loss: 1.4614484610759335
Epoch: 12, loss: 1.312725633321514
Epoch: 13, loss: 1.1795302166133095
Epoch: 14, loss: 1.0642792307975937
Epoch: 15, loss: 0.9687513330442882
Epoch: 16, loss: 0.8934877691799642
Epoch: 17, loss: 0.8373809335043623
Epoch: 18, loss: 0.7977372584586342
Epoch: 19, loss: 0.7708473483460756
Epoch: 20, loss: 0.7528750783084744
Epoch: 21, loss: 0.7406542710439427
Epoch: 22, loss: 0.7319877374207977
Epoch: 23, loss: 0.7255094549275494
Epoch: 24, loss: 0.7204149532675947
Epoch: 25, loss: 0.7162370259169698
Epoch: 26, loss: 0.7127004345303929
Epoch: 27, loss: 0.7096373519723966
Epoch: 28, loss: 0.7069404442085437
Epoch: 

In [ ]:
model.weights

tensor([[-0.0487],
        [-0.1460],
        [-0.3871],
        [ 0.5152],
        [-0.0796],
        [ 0.4104],
        [-0.3965],
        [ 0.2234],
        [-0.0233],
        [-0.0879],
        [-0.2225],
        [-0.2184],
        [ 0.0801],
        [ 0.0692],
        [-0.1324],
        [-0.3669],
        [ 0.1012],
        [ 0.0686],
        [ 0.3572],
        [ 0.2360],
        [ 0.0915],
        [ 0.3528],
        [-0.2570],
        [-0.0617],
        [ 0.0625],
        [ 0.1685],
        [-0.3054],
        [ 0.2091],
        [-0.2701],
        [ 0.0306]], dtype=torch.float64, requires_grad=True)

In [ ]:
model.bias

tensor([-0.4764], dtype=torch.float64, requires_grad=True)

## Evaluation

In [ ]:
# model evaluation
with torch.no_grad():
  y_pred = model.forward(X_test_tensor)
  y_pred = (y_pred > 0.5).float()

  accuracy = (y_pred == y_test_tensor).float().mean()
  print(f'Accuracy: {accuracy.item()}')

Accuracy: 0.6034164428710938
